[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
fractionalization = "481bmy6UgmE4EkwUPXsSTqeAi6tNVe3DJZD3hcSJFuWD"

[programs.localnet]
fractionalization = "481bmy6UgmE4EkwUPXsSTqeAi6tNVe3DJZD3hcSJFuWD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "utils/program_data/metadata_program.so"

[[test.genesis]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
program = "utils/program_data/bubblegum.so"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "utils/program_data/log_wrapper.so"

[[test.genesis]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program = "utils/program_data/compression_program.so"
